# Generated by Django 3.2.3 on 2021-05-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210525_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.empresa'),
        ),
    ]
